---
- name: include os specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: tweaks.yml
  static: false
  when: enable_performance_tweaks == true

- include: env.yml
  static: false
  when: include_env == true

- include: java.yml

- include: cassandra_repo.yml

- name: install cassandra and cassandra tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - cassandra
    - cassandra-tools

- name: setup cassandra configuration file
  template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_conf_dir }}/cassandra.yaml"
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    force: true

- name: start and enable cassandra service
  service:
    name: cassandra
    state: restarted
    enabled: yes
  changed_when: false
