---
- name: configure file descriptors limit
  pam_limits:
    domain: "{{ item.domain }}"
    limit_type: "{{ item.type }}"
    limit_item: "{{ item.item }}"
    value: "{{ item.value }}"
  with_items:
    - domain: 'cassandra'
      type: '-'
      item: 'memlock'
      value: 'unlimited'
    - domain: 'cassandra'
      type: '-'
      item: 'nofile'
      value: '100000'
    - domain: 'cassandra'
      type: '-'
      item: 'nproc'
      value: '32768'
    - domain: 'cassandra'
      type: '-'
      item: 'as'
      value: 'unlimited'
    - domain: '*'
      type: 'soft'
      item: 'nofile'
      value: '65532'
    - domain: '*'
      type: 'hard'
      item: 'nofile'
      value: '65532'
    - domain: 'root'
      type: '-'
      item: 'memlock'
      value: 'unlimited'
    - domain: 'root'
      type: '-'
      item: 'nofile'
      value: '100000'
    - domain: 'root'
      type: '-'
      item: 'nproc'
      value: '32768'
    - domain: 'root'
      type: '-'
      item: 'as'
      value: 'unlimited'

- name: configure sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    reload: true
    sysctl_file: '/etc/sysctl.d/cassandra.conf'
  with_items:
    - name: net.ipv4.tcp_tw_reuse
      value: 1
    - name: vm.overcommit_memory
      value: 1
    - name: vm.zone_reclaim_mode
      value: 0
    - name: vm.max_map_count
      value: 131072
    - name: net.core.rmem_max
      value: 16777216
    - name: net.core.wmem_max
      value: 16777216
    - name: net.core.rmem_default
      value: 16777216
    - name: net.core.wmem_default
      value: 16777216
    - name: net.core.optmem_max
      value: 40960
    - name: net.ipv4.tcp_rmem
      value: '4096 87380 16777216'
    - name: net.ipv4.tcp_wmem
      value: '4096 65536 16777216'
